version: '3'
services:
  back-end:
    build: ./back
    volumes:
      - .:/src/back
      - /src/back/node_modules
    environment:
      PORT: 4000
      NODE_ENV: development
    ports:
      - 4000:4000
  front-end:
    build: ./front
    volumes:
      - .:/src/front
      - /src/front/node_modules
    environment:
      PORT: 5000
    ports:
      - 5000:5000
  minio:
    image: minio/minio
    volumes:
      - /usr/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio-storage
    command: server /data
